name: document_camera
description: "Example app for document_camera_frame package (document scan + optional OCR)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Local package (use path). For published version: document_camera_frame: ^2.0.5
  document_camera_frame:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
